compute_environment: LOCAL_MACHINE
distributed_type: 'NO'
downcast_bf16: 'no'
gpu_ids: '0'
machine_rank: 0
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
use_cpu: false
dynamo_backend: 'no'
megatron_lm_tp_degree: 1
megatron_lm_pp_degree: 1
megatron_lm_sequence_parallelism: false
deepspeed_config: {}
fsdp_config: {} 