#! /bin/sh
#
# rlm          Start/Stop rlm
#

#----------------------------------------------------------------
#----------------------------------------------------------------
#----------------------------------------------------------------
# NOTE:
# NOTE: Configure these 5 variables for your system
# NOTE:

# Set rlmuser to the user under which rlm will run
rlmuser=ahada

# Set rlmdir to the directory where the rlm binaries are found
rlmdir=/opt/rlm

# Set licfile to the path to the license file
licfile=$rlmdir/solidangle.lic

# Set debuglog to the path to the debug log
debuglog=+$rlmdir/rlm_lic.dlog
#----------------------------------------------------------------
#----------------------------------------------------------------
#----------------------------------------------------------------

start() {
echo $debuglog
	su - $rlmuser -c "$rlmdir/rlm -c $licfile -dlog $debuglog &"
}

stop() {
	su - $rlmuser -c "echo 'y' | $rlmdir/rlmutil rlmdown RLM" 
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart)
	stop
	sleep 2
	start
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit 0
